# Use Node LTS
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the client code
COPY client/ ./

# Expose port
EXPOSE 3000

# Start the app
# CMD ["npm", "start"]
CMD ["npm", "start", "--", "--host", "0.0.0.0"]
